### ISSUE TITLE
fading frame rate (-fps) not supported 

### ISSUE THREAD

**Issue by Konfekt** [wavexx/acpilight#12]
On OpenSUSE 15, `/usr/bin/xbacklight` does not support the switch `-fps`. Instead, computations such as
```sh
steps=$(( "$fade_time" * "$steps_per_second" / 1000 ))
xbacklight -set $brightness -time $fade_time -step "$steps"
```
have to be done. Perhaps, for better compatibility, this could be mentioned in `Differences from xbacklight`.

**Comment by wavexx** [comment]
Will do. -fps is something I added later, as using -steps and -time always made little sense to me.
