### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by wavexx** [wavexx/acpilight#13]
As a moniker, I'll be moving most of my repos to GitLab during the next few days. This includes acpilight.

I've been waiting to do this for a long time as I do find gitlab superior and I'm using gitlab in many more contextes than simply gitlab.com. I never switched because of network effects, but now I'll use the acquisition news to jump the shark!

See you on the other side!

**Comment by Jamim** [comment]
Hi @wavexx,

I did not found `acpilight` [on GitLab](https://gitlab.com/users/wavexx/projects), so I created the PR #14 here on GitHub.

Regards,
Aliaksei
