### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Mic92** [wavexx/acpilight#3]
I want to package this script for Nixos.
It would help me, if you could publish a release.
Is this possible?

**Comment by wavexx** [comment]
I would be ok with this. I'd love to have a man-page in there though (even though adapting the xbacklight manpage should be fine if properly licensed).

**Comment by ghost** [comment]
This will also help on Gentoo where I have added it as sys-power/acpilight.  The man page would be nice, but not required.

**Comment by wavexx** [comment]
@grknight could you have a look at the new man page?
If this is satisfactory, I can tag this as 1.0

**Comment by ghost** [comment]
@wavexx looks good to me

**Comment by wavexx** [comment]
On Thu, Feb 23 2017, Brian Evans wrote:
> @wavexx looks good to me

Then we have a release.
