### ISSUE TITLE
Full xbacklight compatibility missing

### ISSUE THREAD

**Issue by Pelado-Mat** [wavexx/acpilight#5]
In xbacklight 1.2.1 you can set the backlight level without using options:
```
 $ /usr/bin/xbacklight +10
```

```
usage: /usr/bin/xbacklight [options]
  where options are:
  -display <display> or -d <display>
  -help
  -set <percentage> or = <percentage>
  -inc <percentage> or + <percentage>
  -dec <percentage> or - <percentage>
  -get
  -time <fade time in milliseconds>
  -steps <number of steps in fade>
``` 

Are there any plans to implement this?

**Comment by wavexx** [comment]
On Wed, Nov 23 2016, Matias wrote:

> In xbacklight 1.2.1 you can set the backlight level without using options:
> 
> ```
>  $ /usr/bin/xbacklight +10
> ```

Hah, never actually used xbacklight this way.
Should be doable.

Does xbacklight actually allow combinations of -flag with +10, or is it
supported only as the first argument?
