### ISSUE TITLE
Wanted to let you know

### ISSUE THREAD

**Issue by xenowaza** [wavexx/acpilight#8]
I am running Arch on a mid-2014 Macbook Pro (11,3), and I am able to control keyboard backlighting with the following:

`xbacklight -ctrl smc::kbd_backlight -inc 5`

Also, I successfully applied your udev rules unaltered, and after adding my user to the `video` group, I am good to go. In case you want it, here is the exact code I am using in `.config/i3/config`:

`bindsym XF86KbdBrightnessUp exec --no-startup-id xbacklight -ctrl smc::kbd_backlight -inc 5`
`bindsym XF86KbdBrightnessDown exec --no-startup-id xbacklight -ctrl smc::kbd_backlight -dec 5`

Thank you, @wavexx and other contributors, for your hard work; it is much appreciated.

**Comment by wavexx** [comment]
Thanks a lot! I added the info in the README. As for the i3 rules, it would be nice to add them to the archwiki instead. Either on the i3 page or here: https://wiki.archlinux.org/index.php/MacBookPro11,x#Keyboard_backlight

**Comment by xenowaza** [comment]
Happy to help out, and thanks for the tip -- I'll look into that now.
